BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        #text: 'one'
        text: 'Clear'
        on_press: app.clear_up()
    Button:
        #text: 'two'
        text: ''
        id: input_name
        #text: ''

    Button:
        #text: 'three'
        text: 'Greet'
        on_press: app.handle_greet()
        id: output_label
    Button:
        text: 'four'
    Label:
        color: (1,1,0,1)
        text: 'Enter your name'